### ISSUE TITLE
defence

### ISSUE THREAD

**Issue by Night-Sky1970** [kcouck/xvx-hq#10]
i went to defence  and did get this error msg

![afbeelding](https://user-images.githubusercontent.com/51300743/59019955-4a2d8c80-8849-11e9-8c7a-4d6c8a655312.png)

**Comment by Night-Sky1970** [comment]
i also did get this when asking the statistics for today.  on planetarion - defence - statistisc
![afbeelding](https://user-images.githubusercontent.com/51300743/59020093-937ddc00-8849-11e9-8748-225c3466a98a.png)

**Comment by kcouck** [comment]
Can you make a new ticket for your original issue? The statistics are fixed
