### ISSUE TITLE
Arbiter and working with something btween ( )

### ISSUE THREAD

**Issue by Night-Sky1970** [kcouck/xvx-hq#3]
ik probeerde iemand op intel te zetten en kreeg deze melding

https://pastebin.com/8JKWtqYG

ik had iets tussen ( )  gezet.. en dat pakte de webby niet

nadat ik de haakjes weg had gehaald werkte het wel.
opzich geen groot probleem natuurlijk maar ik denk ik maak er toch ff melding van :D

**Comment by kcouck** [comment]
Nick was too long (max=30 char)
(double space between Armaeddon and '(' makes it 31 char)
