### ISSUE TITLE
odd error on recalled ships

### ISSUE THREAD

**Issue by Night-Sky1970** [kcouck/xvx-hq#8]
![afbeelding](https://user-images.githubusercontent.com/51300743/59010513-d9c74100-8831-11e9-8458-4d9d528b1747.png)

included what i pasted

[060620190806.zip](https://github.com/kcouck/xvx-hq/files/3260196/060620190806.zip)

**Comment by Night-Sky1970** [comment]
Action failed: setting fleet as recalled 1154. A database error occured (message: Out of range value for column 'recalled' at row 1, code: 1264).
Action failed: setting fleet as recalled 1176. A database error occured (message: Out of range value for column 'recalled' at row 1, code: 1264).
Action failed: setting fleet as recalled 1181. A database error occured (message: Out of range value for column 'recalled' at row 1, code: 1264).
Action failed: setting fleet as recalled 1189. A database error occured (message: Out of range value for column 'recalled' at row 1, code: 1264).
Action failed: setting fleet as recalled 1168. A database error occured (message: Out of range value for column 'recalled' at row 1, code: 1264).
Action failed: setting fleet as recalled 1151. A database error occured (message: Out of range value for column 'recalled' at row 1, code: 1264).
Action failed: setting fleet as recalled 1166. A database error occured (message: Out of range value for column 'recalled' at row 1, code: 1264).
Action failed: setting fleet as recalled 1167. A database error occured (message: Out of range value for column 'recalled' at row 1, code: 1264).
Action failed: setting fleet as recalled 1220. A database error occured (message: Out of range value for column 'recalled' at row 1, code: 1264).

**Comment by Night-Sky1970** [comment]
now i get the same also with galstatus.

https://pastebin.com/NGGf7Zq4

![afbeelding](https://user-images.githubusercontent.com/51300743/59018080-5879a980-8845-11e9-915e-9f9d2825a0e7.png)

**Comment by kcouck** [comment]
Issue with the size of the field in DB.
